name: EAS Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Make credentials file
        run: echo ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY_BASE64 }} | base64 -d > googleServiceAccountKey.json
      - name: Verify key
        run: cat googleServiceAccountKey.json
      # - name: Build on EAS
      #   run: eas build --platform android --non-interactive